---
abstract: 'Prebuilt Raw SQL Statement Builder'
author:
  - 'Yusuke Kawasaki'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.55
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Pico
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DBI: 1.21
  Exporter: 0
  File::Spec: 0
  Scalar::Util: 0
version: 0.02
